#include "legacy_cpu.h"
#include <stdint.h>

/* Original DMA channel interrupt and original byte range 0x01e2..0x046b.
 * C owns constants, SRAM/MMIO access and internal jumps. Exact ASM
 * retains the ISR frame, flags and private peripheral/call contracts.
 * No independent functional validation of a rejected plain-C ISR
 * is recorded; acceptance is complete canonical FLASH equality. */
void DMA_CH1_vect_isr(void)
{
    register uint8_t r2 asm("r2");
    register uint8_t r16 asm("r16");
    register uint8_t r17 asm("r17");
    register uint8_t r18 asm("r18");
    register uint8_t r19 asm("r19");
    register uint8_t r20 asm("r20");
    register uint8_t r22 asm("r22");
    register uint8_t r26 asm("r26");
    register uint8_t r27 asm("r27");
    register uint8_t r28 asm("r28");
    register uint8_t r29 asm("r29");
    register uint8_t r30 asm("r30");
    register uint8_t r31 asm("r31");
    asm volatile("push        r31" : : : "memory", "cc");
    asm volatile("in          r31,63" : : : "memory", "cc");
    asm volatile("push        r16" : : : "memory", "cc");
    asm volatile("push        r17" : : : "memory", "cc");
    asm volatile("push        r18" : : : "memory", "cc");
    asm volatile("push        r28" : : : "memory", "cc");
    asm volatile("push        r29" : : : "memory", "cc");
    asm volatile("push        r30" : : : "memory", "cc");
    asm volatile("push        r31" : : : "memory", "cc");
    r17 = 0xa;
    asm volatile("" : "+r" (r17));
L_0000fb:
    asm volatile(".Ldma_L_0000fb:" : : : "memory");
    r16 = *(volatile uint8_t *)0x668;
    asm volatile("" : "+r" (r16));
    asm goto("sbrc        r16,0x4\n\trjmp .Ldma_L_000101" : : : "memory", "cc" : L_000101);
    asm volatile("dec         r17" : : : "memory", "cc");
    asm goto("brbc 1, .Ldma_L_0000fb" : : : "memory", "cc" : L_0000fb);
L_000101:
    asm volatile(".Ldma_L_000101:" : : : "memory");
    r17 = *(volatile uint8_t *)0x124;
    asm volatile("" : "+r" (r17));
    r16 = 0x11;
    asm volatile("" : "+r" (r16));
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x121 = r16;
    r30 = 0x76;
    asm volatile("" : "+r" (r30));
    r31 = 0x2b;
    asm volatile("" : "+r" (r31));
    r28 = 0x39;
    asm volatile("" : "+r" (r28));
    r29 = 0x24;
    asm volatile("" : "+r" (r29));
    r16 = 0x8;
    asm volatile("" : "+r" (r16));
    asm volatile("sub         r16,r17" : : : "memory", "cc");
    asm volatile("eor         r17,r17" : : : "memory", "cc");
    asm volatile("" : "=r" (r16), "=r" (r28));
    r28 += r16;
    asm volatile("" : "+r" (r28));
    asm volatile("adc         r29,r17" : : : "memory", "cc");
    asm volatile("ld          r16,Y+" : : : "memory", "cc");
    asm volatile("cpi         r16,0xaa" : : : "memory", "cc");
    asm goto("brbs 1, .Ldma_L_000116" : : : "memory", "cc" : L_000116);
L_000112:
    asm volatile(".Ldma_L_000112:" : : : "memory");
    asm volatile("lpm         r17,Z+" : : : "memory", "cc");
    asm volatile("cp          r16,r17" : : : "memory", "cc");
    asm goto("brbs 1, .Ldma_L_000130" : : : "memory", "cc" : L_000130);
    goto L_00022c;
L_000116:
    asm volatile(".Ldma_L_000116:" : : : "memory");
    asm volatile("cpi         r17,0x7" : : : "memory", "cc");
    asm goto("brbs 1, .Ldma_L_000120" : : : "memory", "cc" : L_000120);
    asm volatile("inc         r17" : : : "memory", "cc");
    asm volatile("cpi         r28,0x41" : : : "memory", "cc");
    asm goto("brbc 1, .Ldma_L_00011c" : : : "memory", "cc" : L_00011c);
    asm volatile("sbiw        Y,0x8" : : : "memory", "cc");
L_00011c:
    asm volatile(".Ldma_L_00011c:" : : : "memory");
    asm volatile("ld          r16,Y+" : : : "memory", "cc");
    asm volatile("cpi         r16,0xaa" : : : "memory", "cc");
    asm goto("brbs 1, .Ldma_L_000116" : : : "memory", "cc" : L_000116);
    goto L_00022c;
L_000120:
    asm volatile(".Ldma_L_000120:" : : : "memory");
    pm_cpu_disable_irq();
    asm volatile("rcall       FUN_code_0005b4" : : : "memory", "cc");
    asm volatile("bset        7" : : : "memory", "cc");
    r16 = 0x3;
    asm volatile("" : "+r" (r16));
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x2441 = r16;
    asm volatile("pop         r31" : : : "memory", "cc");
    asm volatile("pop         r30" : : : "memory", "cc");
    asm volatile("pop         r29" : : : "memory", "cc");
    asm volatile("pop         r28" : : : "memory", "cc");
    asm volatile("pop         r18" : : : "memory", "cc");
    asm volatile("pop         r17" : : : "memory", "cc");
    asm volatile("pop         r16" : : : "memory", "cc");
    asm volatile("out         63,r31" : : : "memory", "cc");
    asm volatile("pop         r31" : : : "memory", "cc");
    asm volatile("rjmp        PORTF_INT1_vect_isr" : : : "memory", "cc");
    __builtin_unreachable();
L_000130:
    asm volatile(".Ldma_L_000130:" : : : "memory");
    asm volatile("cpi         r28,0x41" : : : "memory", "cc");
    asm goto("brbc 1, .Ldma_L_000133" : : : "memory", "cc" : L_000133);
    asm volatile("sbiw        Y,0x8" : : : "memory", "cc");
L_000133:
    asm volatile(".Ldma_L_000133:" : : : "memory");
    asm volatile("ld          r16,Y+" : : : "memory", "cc");
    asm volatile("cpi         r30,0x7e" : : : "memory", "cc");
    asm goto("brbc 1, .Ldma_L_000112" : : : "memory", "cc" : L_000112);
    asm volatile("eor         r16,r16" : : : "memory", "cc");
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x120 = r16;
    asm volatile("bset        7" : : : "memory", "cc");
    asm volatile("push        r0" : : : "memory", "cc");
    asm volatile("push        r1" : : : "memory", "cc");
    asm volatile("push        r2" : : : "memory", "cc");
    asm volatile("push        r10" : : : "memory", "cc");
    asm volatile("push        r19" : : : "memory", "cc");
    asm volatile("push        r20" : : : "memory", "cc");
    asm volatile("push        r21" : : : "memory", "cc");
    asm volatile("push        r22" : : : "memory", "cc");
    asm volatile("push        r23" : : : "memory", "cc");
    asm volatile("push        r24" : : : "memory", "cc");
    asm volatile("push        r25" : : : "memory", "cc");
    asm volatile("push        r26" : : : "memory", "cc");
    asm volatile("push        r27" : : : "memory", "cc");
    asm volatile("call        FUN_code_000b32" : : : "memory", "cc");
    asm volatile("call        FUN_code_000c20" : : : "memory", "cc");
    r28 = 0x39;
    asm volatile("" : "+r" (r28));
    r29 = 0x24;
    asm volatile("" : "+r" (r29));
    asm volatile("" : "=r" (r28));
    *(volatile uint8_t *)0x118 = r28;
    asm volatile("" : "=r" (r29));
    *(volatile uint8_t *)0x119 = r29;
    asm volatile("eor         r20,r20" : : : "memory", "cc");
    asm volatile("" : "=r" (r20));
    *(volatile uint8_t *)0x11a = r20;
    asm volatile("st          Y+,r18" : : : "memory", "cc");
    asm volatile("st          Y+,r19" : : : "memory", "cc");
    asm volatile("st          Y+,r16" : : : "memory", "cc");
    asm volatile("st          Y,r20" : : : "memory", "cc");
    r16 = 0x4;
    asm volatile("" : "+r" (r16));
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x114 = r16;
    asm volatile("eor         r16,r16" : : : "memory", "cc");
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x115 = r16;
    r16 = 0x94;
    asm volatile("" : "+r" (r16));
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x110 = r16;
L_000161:
    asm volatile(".Ldma_L_000161:" : : : "memory");
    r16 = *(volatile uint8_t *)0x111;
    asm volatile("" : "+r" (r16));
    asm goto("sbrs        r16,0x4\n\trjmp .Ldma_L_000161" : : : "memory", "cc" : L_000161);
    r16 = 0x10;
    asm volatile("" : "+r" (r16));
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x111 = r16;
    r26 = 0x39;
    asm volatile("" : "+r" (r26));
    r27 = 0x24;
    asm volatile("" : "+r" (r27));
    asm volatile("" : "=r" (r26));
    *(volatile uint8_t *)0x12c = r26;
    asm volatile("" : "=r" (r27));
    *(volatile uint8_t *)0x12d = r27;
    asm volatile("eor         r20,r20" : : : "memory", "cc");
    asm volatile("" : "=r" (r20));
    *(volatile uint8_t *)0x12e = r20;
    r16 = 0x8;
    asm volatile("" : "+r" (r16));
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x124 = r16;
    asm volatile("eor         r16,r16" : : : "memory", "cc");
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x125 = r16;
L_000177:
    asm volatile(".Ldma_L_000177:" : : : "memory");
    r16 = *(volatile uint8_t *)0x668;
    asm volatile("" : "+r" (r16));
    asm goto("sbrs        r16,0x4\n\trjmp .Ldma_L_000177" : : : "memory", "cc" : L_000177);
    r16 = *(volatile uint8_t *)0x9c2;
    asm volatile("" : "+r" (r16));
    r16 = *(volatile uint8_t *)0x9c3;
    asm volatile("" : "+r" (r16));
    r16 = 0x84;
    asm volatile("" : "+r" (r16));
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x120 = r16;
L_000182:
    asm volatile(".Ldma_L_000182:" : : : "memory");
    r16 = *(volatile uint8_t *)0x121;
    asm volatile("" : "+r" (r16));
    asm goto("sbrs        r16,0x4\n\trjmp .Ldma_L_000182" : : : "memory", "cc" : L_000182);
    r16 = 0x10;
    asm volatile("" : "+r" (r16));
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x121 = r16;
    asm volatile("ld          r28,X+" : : : "memory", "cc");
    asm volatile("ld          r29,X+" : : : "memory", "cc");
    asm volatile("ld          r30,X+" : : : "memory", "cc");
    asm volatile("adiw        X,0x1" : : : "memory", "cc");
    asm volatile("ld          r0,X+" : : : "memory", "cc");
    asm volatile("ld          r1,X+" : : : "memory", "cc");
    asm volatile("ld          r2,X" : : : "memory", "cc");
    asm volatile("movw        r20,Y" : : : "memory", "cc");
    asm volatile("" : "=r" (r30));
    r22 = r30;
    asm volatile("" : "+r" (r22));
    r26 = 0x39;
    asm volatile("" : "+r" (r26));
    r27 = 0x24;
    asm volatile("" : "+r" (r27));
    asm volatile("" : "=r" (r26));
    *(volatile uint8_t *)0x118 = r26;
    asm volatile("" : "=r" (r27));
    *(volatile uint8_t *)0x119 = r27;
    asm volatile("eor         r16,r16" : : : "memory", "cc");
    asm volatile("st          X+,r16" : : : "memory", "cc");
    asm volatile("st          X+,r16" : : : "memory", "cc");
    asm volatile("st          X+,r16" : : : "memory", "cc");
    asm volatile("st          X,r16" : : : "memory", "cc");
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x11a = r16;
    r16 = 0x4;
    asm volatile("" : "+r" (r16));
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x114 = r16;
    asm volatile("eor         r16,r16" : : : "memory", "cc");
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x115 = r16;
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x116 = r16;
L_0001a7:
    asm volatile(".Ldma_L_0001a7:" : : : "memory");
    r16 = *(volatile uint8_t *)0x668;
    asm volatile("" : "+r" (r16));
    asm goto("sbrs        r16,0x4\n\trjmp .Ldma_L_0001a7" : : : "memory", "cc" : L_0001a7);
    r16 = 0xb4;
    asm volatile("" : "+r" (r16));
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x110 = r16;
    asm volatile("eor         r16,r16" : : : "memory", "cc");
    r26 = 0x35;
    asm volatile("" : "+r" (r26));
    r27 = 0x24;
    asm volatile("" : "+r" (r27));
    asm volatile("st          X+,r16" : : : "memory", "cc");
    asm volatile("st          X+,r16" : : : "memory", "cc");
    asm volatile("st          X+,r16" : : : "memory", "cc");
    asm volatile("st          X,r16" : : : "memory", "cc");
L_0001b5:
    asm volatile(".Ldma_L_0001b5:" : : : "memory");
    asm volatile("call        FUN_code_000b88" : : : "memory", "cc");
L_0001b7:
    asm volatile(".Ldma_L_0001b7:" : : : "memory");
    asm volatile("movw        r16,r0" : : : "memory", "cc");
    asm volatile("" : "=r" (r2));
    r18 = r2;
    asm volatile("" : "+r" (r18));
    asm volatile("sub         r16,r20" : : : "memory", "cc");
    asm volatile("sbc         r17,r21" : : : "memory", "cc");
    asm volatile("sbc         r18,r22" : : : "memory", "cc");
    asm volatile("subi        r16,0xff" : : : "memory", "cc");
    asm volatile("sbci        r17,0xff" : : : "memory", "cc");
    asm volatile("sbci        r18,0xff" : : : "memory", "cc");
    asm volatile("and         r18,r18" : : : "memory", "cc");
    asm goto("brbc 1, .Ldma_L_0001c7" : : : "memory", "cc" : L_0001c7);
    r18 = 0x1;
    asm volatile("" : "+r" (r18));
    asm volatile("cp          r16,r18" : : : "memory", "cc");
    asm volatile("cpc         r17,r18" : : : "memory", "cc");
    asm goto("brbc 0, .Ldma_L_0001c7" : : : "memory", "cc" : L_0001c7);
    r31 = 0x1;
    asm volatile("" : "+r" (r31));
    goto L_0001ca;
L_0001c7:
    asm volatile(".Ldma_L_0001c7:" : : : "memory");
    asm volatile("eor         r16,r16" : : : "memory", "cc");
    r17 = 0x1;
    asm volatile("" : "+r" (r17));
    asm volatile("eor         r31,r31" : : : "memory", "cc");
L_0001ca:
    asm volatile(".Ldma_L_0001ca:" : : : "memory");
    r26 = 0x35;
    asm volatile("" : "+r" (r26));
    r27 = 0x22;
    asm volatile("" : "+r" (r27));
    r18 = *(volatile uint8_t *)0x2435;
    asm volatile("" : "+r" (r18));
    asm volatile("" : "=r" (r18), "=r" (r27));
    r27 += r18;
    asm volatile("" : "+r" (r27));
    r19 = 0x1;
    asm volatile("" : "+r" (r19));
    asm volatile("" : "=r" (r18), "=r" (r19));
    r18 ^= r19;
    asm volatile("" : "+r" (r18));
    asm volatile("" : "=r" (r18));
    *(volatile uint8_t *)0x2435 = r18;
    asm volatile("" : "=r" (r26));
    *(volatile uint8_t *)0x12c = r26;
    asm volatile("" : "=r" (r27));
    *(volatile uint8_t *)0x12d = r27;
    asm volatile("eor         r20,r20" : : : "memory", "cc");
    asm volatile("" : "=r" (r20));
    *(volatile uint8_t *)0x12e = r20;
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x124 = r16;
    asm volatile("" : "=r" (r17));
    *(volatile uint8_t *)0x125 = r17;
    asm volatile("rcall       FUN_code_000236" : : : "memory", "cc");
    r16 = 0x84;
    asm volatile("" : "+r" (r16));
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x120 = r16;
L_0001e2:
    asm volatile(".Ldma_L_0001e2:" : : : "memory");
    r16 = *(volatile uint8_t *)0x121;
    asm volatile("" : "+r" (r16));
    asm goto("sbrs        r16,0x4\n\trjmp .Ldma_L_0001e2" : : : "memory", "cc" : L_0001e2);
    r16 = 0x10;
    asm volatile("" : "+r" (r16));
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x121 = r16;
    asm volatile("and         r31,r31" : : : "memory", "cc");
    asm goto("brbs 1, .Ldma_L_000204" : : : "memory", "cc" : L_000204);
L_0001eb:
    asm volatile(".Ldma_L_0001eb:" : : : "memory");
    r18 = *(volatile uint8_t *)0x668;
    asm volatile("" : "+r" (r18));
    asm goto("sbrs        r18,0x4\n\trjmp .Ldma_L_0001eb" : : : "memory", "cc" : L_0001eb);
    asm volatile("eor         r16,r16" : : : "memory", "cc");
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x110 = r16;
    r26 = 0x39;
    asm volatile("" : "+r" (r26));
    r27 = 0x24;
    asm volatile("" : "+r" (r27));
    asm volatile("" : "=r" (r26));
    *(volatile uint8_t *)0x118 = r26;
    asm volatile("" : "=r" (r27));
    *(volatile uint8_t *)0x119 = r27;
    asm volatile("eor         r16,r16" : : : "memory", "cc");
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x11a = r16;
    r16 = 0x8;
    asm volatile("" : "+r" (r16));
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x114 = r16;
    asm volatile("eor         r16,r16" : : : "memory", "cc");
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x115 = r16;
    r16 = 0xb4;
    asm volatile("" : "+r" (r16));
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x110 = r16;
L_000204:
    asm volatile(".Ldma_L_000204:" : : : "memory");
    asm volatile("call        FUN_code_000b9d" : : : "memory", "cc");
    asm volatile("call        FUN_code_000b59" : : : "memory", "cc");
    asm goto("brbs 0, .Ldma_L_00020f" : : : "memory", "cc" : L_00020f);
    asm volatile("and         r21,r21" : : : "memory", "cc");
    asm goto("brbs 1, .Ldma_L_00020c" : : : "memory", "cc" : L_00020c);
    goto L_0001b7;
L_00020c:
    asm volatile(".Ldma_L_00020c:" : : : "memory");
    asm volatile("call        FUN_code_000b9d" : : : "memory", "cc");
    goto L_0001b5;
L_00020f:
    asm volatile(".Ldma_L_00020f:" : : : "memory");
    asm volatile("call        FUN_code_000b9d" : : : "memory", "cc");
    asm volatile("call        FUN_code_000bb9" : : : "memory", "cc");
    r26 = 0x3d;
    asm volatile("" : "+r" (r26));
    r27 = 0x24;
    asm volatile("" : "+r" (r27));
    asm volatile("st          X+,r18" : : : "memory", "cc");
    asm volatile("st          X+,r19" : : : "memory", "cc");
    asm volatile("st          X+,r16" : : : "memory", "cc");
    asm volatile("st          X+,r17" : : : "memory", "cc");
    asm volatile("rcall       FUN_code_000236" : : : "memory", "cc");
    asm volatile("eor         r16,r16" : : : "memory", "cc");
    asm volatile("" : "=r" (r16));
    *(volatile uint8_t *)0x100 = r16;
    asm volatile("call        FUN_code_000b3f" : : : "memory", "cc");
    asm volatile("pop         r27" : : : "memory", "cc");
    asm volatile("pop         r26" : : : "memory", "cc");
    asm volatile("pop         r25" : : : "memory", "cc");
    asm volatile("pop         r24" : : : "memory", "cc");
    asm volatile("pop         r23" : : : "memory", "cc");
    asm volatile("pop         r22" : : : "memory", "cc");
    asm volatile("pop         r21" : : : "memory", "cc");
    asm volatile("pop         r20" : : : "memory", "cc");
    asm volatile("pop         r19" : : : "memory", "cc");
    asm volatile("pop         r10" : : : "memory", "cc");
    asm volatile("pop         r2" : : : "memory", "cc");
    asm volatile("pop         r1" : : : "memory", "cc");
    asm volatile("pop         r0" : : : "memory", "cc");
L_00022c:
    asm volatile(".Ldma_L_00022c:" : : : "memory");
    asm volatile("pop         r31" : : : "memory", "cc");
    asm volatile("pop         r30" : : : "memory", "cc");
    asm volatile("pop         r29" : : : "memory", "cc");
    asm volatile("pop         r28" : : : "memory", "cc");
    asm volatile("pop         r18" : : : "memory", "cc");
    asm volatile("pop         r17" : : : "memory", "cc");
    asm volatile("pop         r16" : : : "memory", "cc");
    asm volatile("out         63,r31" : : : "memory", "cc");
    asm volatile("pop         r31" : : : "memory", "cc");
    asm volatile("reti" : : : "memory", "cc");
    __builtin_unreachable();
}
